### ISSUE TITLE
python3 issues on weewx 4.0.0

### ISSUE THREAD

**Issue by TonyF21** [wmadill/weewx-S3upload#1]
Attempting to port this script over to weewx 4.0.0 using pthon3.

A few syntax errors resolved since changes on python3.

path changes on default directories used under weewx 4.0.0.

Biggest issue is getting S3 to work correctly.  Stuck at 

/weewxd: s3uploadgenerator: s3cmd output: b'ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.'
May  4 10:15:23 WXraspberrypi /weewxd: s3uploadgenerator: s3cmd output: b'ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.'

Keys are correct since I can access bucket manually via s3cmd.

Any plans to update for laterest version of weewx???

Thank you,

**Comment by wmadill** [comment]
What version of S3cmd are you running? There is an FAQ on it's project site that says there was a bug that crept in on 0.9.5 that got fixed in 0.9.8.4. But that's a pretty old version since they are now at 2.1.0.

I have not (as you can tell ;) done any maintenance on this for quite a while and have been ignoring weewx 4.0 but I guess it's time to get moving on porting my extensions over. If you have a port to python3, I'd be delighted to get a pull request.

Thanks,

Bill

**Comment by TonyF21** [comment]
Yup.. Running 2.1.0 version of S3cmd.  I loaded weewx 4.0.0 originally on an older RPI 1B from many moons ago. Worked for many years np on older version of weewx.  Decided to upgrade to 4.0.0 but the 1B couldnt keep up. Loaded on RPI 3B now and works great on Raspbian 'buster' version of OS . Saw your implementation and was excited to try it on AWS since FTP is throttled lately on my ISP.  I have a .deb installation of weewx 4.0.0 and didn't use setup.py, hence the different directory locations of working bits of weewx.  I installed your extension using "wee_extension" which put stuff in different locations also.  I only fixed the syntax errors on S3upload.py that I assumed python3 complained about and file locations unique to my rpi and extension install.  I checked my "default" python version today, it showed 2.7.16 not 3.7.3 which is also installed.  The syntax errors I thought were unique to version 3 but I guess maybe not. You'll find the syntax errors quickly once you run it on a newer version of python.  I am not a SW guru by any chance but know enough to poke around.  Like any linux issue. Once you update one thing, it avalanches from there.

Give it a shot it you have the time.

Thanks,

TonyF

**Comment by wmadill** [comment]
Hi Tony. I did an weewx installation using setup.py in a VM running buster using the simulator driver. It took a while to set up--it's the one thing led to another and to another... Sorry for delay. I tripped over the syntax errors and fixed them locally. I got the extension to run enough to upload the html to a different S3 bucket successfully before it died with an exception I haven't fixed yet. But it uploaded just fine.

So now I wonder if there is something about the s3cmd configuration that is different. I have not enabled any encryption either for the upload (https) or for the data in the S3 bucket. In fact, my .s3cfg is all defaults except for the access_key and secret_key. Are you setting anything else?

Meanwhile, I'll (slowly) work on getting a clean uploader extension. 

Bill

**Comment by TonyF21** [comment]
Thanks for the update.

I used the standard installation recommended for debian based systems which installed the DEB package.  I didnt use setup.py .  I'll try doing it again using setup.py  to avoid having weewx files and directories installed in various locations rather than under one directory.  Probably later in the week thou since things are starting to get busy now .

TonyF

**Comment by wmadill** [comment]
Hard to see that the weewx installation method is the problem from the error you reported. It seems more like an s3cmd or AWS S3 bucket issue. Did you install s3cmd from the Debian repo or directly from the s3tools site? 

I am finding all sorts of dumb things in the code I wrote so I'm opening issues and then going to try to get a clean version back to github in a few days--hopefully before you need it. Since this is a just-before-bedtime project (when I'm, well, not exactly at my peak performance), progress is slow.

Once I get the code working the way it should have been originally, I'll try various encryption schemes to see if I can get the s3cmd error you got.

Bill

**Comment by wmadill** [comment]
After a long delay, I just committed the python 3/weewx 4 version of S3upload. Haven't yet set the tags--running out of time tonight.

I do not know if this runs on python 2/weewx 3 but will try it out over the next few days and merge any changes needed when I figure them out.

Let me know if you've made any progress on the signature errors and if you find any problems in this new version.

Bill

**Comment by TonyF21** [comment]
Hi Bill,

I downloaded s3cmd from website s3tools.org

TonyF
